name: Build and Publish lily-pwsh Image

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build sterile image with installer script included
        run: |
          docker build -t ghcr.io/revpixel/lily-pwsh:latest .

      - name: Push image
        run: |
          docker push ghcr.io/revpixel/lily-pwsh:latest
